FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Add cuquantum autodetection script
COPY install_cuquantum.py .
RUN python install_cuquantum.py

COPY . .

CMD ["python", "main.py"]



